# Introduction to relational databases

## Why use a relational database?

Here are some of the benefits of using a database to store your data - as opposed to a .csv, .xml, or any other file format:

- you can better manage access (e.g. you can set who is the admin, who can read, who can write, etc.)
- you can collaborate and have many parallel users using the data
- databases are designed to scale and handle large amount of data
- the database schema can be expanded
- relational database can also enforce certain standards such as having a unique value as primary key and thus avoid data quality issues
- relational databases can also enforce data type, e.g. a database can prevent someone from entering an invalid date or an number instead of a name, etc.

## Database schema

A relational database schema represents the connections between different sets of data each capture in a table.

In order to connect tables together, we use a key - also known as primary key - so that data from different takes can be matched. In Excel, you would use a VLOOKUP function to enrich a table with data from another table using a column that is shared amongst the two tables.

<img src="https://nico.nexgate.ch/images/schema.png" width='80%' />

Question: guess which tables are linked with?
- 1:1 relationships
- 1:N relationships
- N:N relationships
- N:1 relationships

## Parallel with Excel

<img src="https://nico.nexgate.ch/images/vlookup.png" width='100%' />

Question: what limitations do you see in using Excel and vlookup?

# Data storage

* step 1. go to http://data.world
* step 2. create an account or log in via  google
* step 3. search for "ZHAW" and select the Data Analysis Fundamentals dataset
* step 4. write a query (or pick an existing one)
* step 5. click on the download option and select "URL"
* step 6. copy the URL in the read_csv statement below in this workbook

In [1]:
import pandas as pd

# Accessing dataset hosted on data.world

## Accessing a table

In [2]:
# accessing a table hosted on data.world
df = pd.read_csv('https://query.data.world/s/5abh3qmxekqnegwbs5dndnlojtak5d?dws=00000',encoding='latin-1',sep=';')

In [3]:
df.head()

,Année,No de la commune,Nom de la commune,No du district,Nom du district,No du canton,Canton,Nom du canton,Unité,Nombre
0,1850,1,Aeugst,101,Affoltern,1,ZH,Zürich,Habitants - Total,647.0
1,1850,1,Aeugst,101,Affoltern,1,ZH,Zürich,Nationalité - Suisse,646.0
2,1850,1,Aeugst,101,Affoltern,1,ZH,Zürich,Nationalité - Etranger,1.0
3,1850,1,Aeugst,101,Affoltern,1,ZH,Zürich,Sexe - Homme,320.0
4,1850,1,Aeugst,101,Affoltern,1,ZH,Zürich,Sexe - Femme,327.0

## Accessing a query

SQL stands for Structured Query Language. It is a query language which lets you interract with relational databases.

Using SQL, you can:

- filter data (equivalent to using one or several masks in python), 
- group and aggregate data (equivalent to using groupby combined with an aggregation funciton in python)
- sort data (equivalent to using sort_values in pandas)
- and much more...

### Creating and saving your own database queries

Steps to create and save your query:

STEP 1: create your SQL query, click Download and choose Save to Dataset or Project

<img src="https://nico.nexgate.ch/images/SQL_query_Thalwil.png" width='60%' />

STEP 2: Change the name (as needed) and save it to your own dataset (or,if you are not the owner, to a new project)

<img src="https://nico.nexgate.ch/images/create_new_dataset.png" width='60%' />

STEP 3: Choose your project name and make sure you set it as public

<img src="https://nico.nexgate.ch/images/set_public.png" width='60%' />

STEP 4: Now that you have your new resource, you can use the Share URL link to Python

<img src="https://nico.nexgate.ch/images/own_project.png" width='60%' />

### Retrieving the output form your SQL queries

In [4]:
import pandas as pd
df2 = pd.read_csv('https://query.data.world/s/xoirphbb32s7um6lqxtan5gkkcvmnn?dws=00000')

In [5]:
df2.head()

,annee,no_de_la_commune,nom_de_la_commune,no_du_district,nom_du_district,no_du_canton,canton,nom_du_canton,unite,nombre
0,1850,141,Thalwil,106,Horgen,1,ZH,Zürich,Habitants - Total,1889.0
1,1850,141,Thalwil,106,Horgen,1,ZH,Zürich,Nationalité - Suisse,1826.0
2,1850,141,Thalwil,106,Horgen,1,ZH,Zürich,Nationalité - Etranger,63.0
3,1850,141,Thalwil,106,Horgen,1,ZH,Zürich,Sexe - Homme,939.0
4,1850,141,Thalwil,106,Horgen,1,ZH,Zürich,Sexe - Femme,950.0

In [6]:
import pandas as pd
df3 = pd.read_csv('https://query.data.world/s/kpx624mtdi3b7r3gnbrhodovjekjs3?dws=00000')
df3.head()

,annee,no_de_la_commune,nom_de_la_commune,no_du_district,nom_du_district,no_du_canton,canton,nom_du_canton,unite,nombre
0,1880,141,Thalwil,106,Horgen,1,ZH,Zürich,Langue - Allemand,3227
1,1880,141,Thalwil,106,Horgen,1,ZH,Zürich,Langue - Français,45
2,1888,141,Thalwil,106,Horgen,1,ZH,Zürich,Langue - Allemand,3909
3,1888,141,Thalwil,106,Horgen,1,ZH,Zürich,Langue - Français,30
4,1900,141,Thalwil,106,Horgen,1,ZH,Zürich,Langue - Allemand,6211

In [7]:
df4 = pd.read_csv('https://query.data.world/s/2pt3bq6d6szrblcjzojajfqzbntgbp?dws=00000')

In [8]:
df4.head()

,annee,no_de_la_commune,nom_de_la_commune,no_du_district,nom_du_district,no_du_canton,canton,nom_du_canton,unite,nombre
0,1850,141,Thalwil,106,Horgen,1,ZH,Zürich,Habitants - Total,1889.0
1,1850,141,Thalwil,106,Horgen,1,ZH,Zürich,Nationalité - Suisse,1826.0
2,1850,141,Thalwil,106,Horgen,1,ZH,Zürich,Nationalité - Etranger,63.0
3,1850,141,Thalwil,106,Horgen,1,ZH,Zürich,Sexe - Homme,939.0
4,1850,141,Thalwil,106,Horgen,1,ZH,Zürich,Sexe - Femme,950.0

# Optional material for your project

## Combining data from multiple dataframes

First you need to think about how you want to combine the data.

Here are some 2 ways of combining data:

### "vlookup-style" enrichment

This is similar to doing a vlookup in Excel to add 1 or several columns of data from another table. -> use the Pandas funciton merge:


```Python
pd.merge(df1,df2,left_on='left_key', right_on='right_key')
```

Note: lookup the documentation. there are a lot more options such as using "how" to define if you want an inner join, an outter join, a left or a right join.

### stack them on top of each other

You have multiple files with exactly the same column headers and no data overlap. For instance, you have an employee list from employees in Switzerland, and another employee list from employees outside of Switzerland -> use the Pandas funciton concat:

```Python
pd.concat(([df1,df2]))
```

note: if the indexes of your dataframes overlap, then you can add another parameter to ignore the overlap and treat each line of data as a new line (even if it has the same index number in df1 and df2), e.g.

```Python
pd.concat([df1,df2], ignore_index=True)
```

## Avoiding errors when changing values


It is very common to get an error when one tries to modify some values in a dataframe.

Typically, one would get an error like the one below:

```
/tmp/ipykernel_7254/3546892955.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead
```
  
Frustrating as it may, it can be resolved relatively easily, let's look at it!

In [14]:
df = pd.read_csv('https://query.data.world/s/5abh3qmxekqnegwbs5dndnlojtak5d?dws=00000',encoding='latin-1',sep=';')

In [15]:
df.head(3)

,Année,No de la commune,Nom de la commune,No du district,Nom du district,No du canton,Canton,Nom du canton,Unité,Nombre
0,1850,1,Aeugst,101,Affoltern,1,ZH,Zürich,Habitants - Total,647.0
1,1850,1,Aeugst,101,Affoltern,1,ZH,Zürich,Nationalité - Suisse,646.0
2,1850,1,Aeugst,101,Affoltern,1,ZH,Zürich,Nationalité - Etranger,1.0

In [16]:
# let's create a mask to filter data for 1 city in canton Zurich:

mask = df['Nom de la commune'] == 'Aeugst am Albis'

In [19]:

# let's imagine we want to change the "No du district" for all rows which are in the city of Aeugst am Albis and set the new value to 999

# if you run this code, you will get an error message
df[mask]['No du district']= 999

/tmp/ipykernel_7254/1775732747.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[mask]['No du district']= 999

The reason is that we filtered view is actually an in-memory copy of a portion of the dataframe.

In other words, we are asking Pandas to show us specific rows of data using a mask. The output does not point to the same memory location used to store the orignal dataframe. Pandas allocates a new space in memory to store the filtered rows.

Thus, when you try to assign a new value to these rows, you get an error because you can't modify the original dataframe since you are pointing to a different place in memory.

So, how do I fix it?

you need to use the .loc funciton with 2 parameters within square brackets "[]":

- the 1st parameter is your mask -> it indicates the range of rows you want to modify
- the 2nd parameter is the column(s) you want to modify

You then you the equal sign "=" to asssign the new value(s). In our example the value 999.

see the code below:

In [20]:
# set the "no du district to 999 for all rows which are in the city of Aeugst am Albis"

df.loc[mask,'No du district'] = 999

In [22]:
# let's verify the output

df[mask].head(3)

,Année,No de la commune,Nom de la commune,No du district,Nom du district,No du canton,Canton,Nom du canton,Unité,Nombre
782600,1980,1,Aeugst am Albis,999,Affoltern,1,ZH,Zürich,Population résidante - Total,866.0
782601,1980,1,Aeugst am Albis,999,Affoltern,1,ZH,Zürich,Nationalité - Suisse,832.0
782602,1980,1,Aeugst am Albis,999,Affoltern,1,ZH,Zürich,Nationalité - Etranger,34.0